### PR TITLE
Restruct

### PR DESCRIPTION
**Pull request by harjotgill**
cc: @luhkevin Re-organized the docs. Would be worthwhile to publish to top level when we release v1.3.0.

### CODE REVIEW

**Comment by luhkevin** [comment]
Taking a look at this now.

**Comment by luhkevin** [comment]
@harjotgill Looks good, but I have a small suggestion. Can we use dashes instead of underscores? e.g. `user-guide` instead of `user_guide`, or `http://docs.netsil.com/user-guide/alerts/#overview` vs `http://docs.netsil.com/user_guide/alerts/#overview` This would look nicer in customer-facing URLs in the future.

If you're okay with this, I've already made and tested this change in a commit, and I can push it directly to this branch.

**Comment by harjotgill** [comment]
Sure, let’s change it.

**Comment by luhkevin** [comment]
Merge when you're ready.

**Pull request merged**
